use proc_macro2::TokenStream as TokenStream2;
use quote::quote;

// NOTE: contains compilation code that involves intrinsics
// generated by `#[derive(Parser)]` macro. It is better to keep
// such code in one place to simplify refactoring if parser
// internals change.
macro_rules! gen_parser_intrinsics {
    (state_enter_flag) => {
        quote! { self.__state_enter }
    };

    (is_last_input) => {
        quote! { input.is_last() }
    };
}

pub trait Compile {
    fn compile(&self) -> TokenStream2;
}
